[2022-10-13T21:33:15.417+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: trabalho2.also_run_this scheduled__2022-10-09T00:00:00+00:00 [queued]>
[2022-10-13T21:33:15.432+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: trabalho2.also_run_this scheduled__2022-10-09T00:00:00+00:00 [queued]>
[2022-10-13T21:33:15.432+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T21:33:15.432+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-13T21:33:15.432+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T21:33:15.454+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): also_run_this> on 2022-10-09 00:00:00+00:00
[2022-10-13T21:33:15.461+0000] {standard_task_runner.py:54} INFO - Started process 285 to run task
[2022-10-13T21:33:15.470+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trabalho2', 'also_run_this', 'scheduled__2022-10-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/***_titanic.py', '--cfg-path', '/tmp/tmp3rgrpdq5']
[2022-10-13T21:33:15.471+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask also_run_this
[2022-10-13T21:33:15.472+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/***_titanic.py
[2022-10-13T21:33:15.497+0000] {logging_mixin.py:117} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:3425 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-10-13T21:33:15.844+0000] {task_command.py:384} INFO - Running <TaskInstance: trabalho2.also_run_this scheduled__2022-10-09T00:00:00+00:00 [running]> on host b572315ae1c7
[2022-10-13T21:33:15.993+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Marcos Vieira
AIRFLOW_CTX_DAG_ID=trabalho2
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-10-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-09T00:00:00+00:00
[2022-10-13T21:33:15.995+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-10-13T21:33:15.995+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -L -o" + target_dir + target_file + " " + source_file']
[2022-10-13T21:33:16.021+0000] {subprocess.py:86} INFO - Output:
[2022-10-13T21:33:16.027+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2022-10-13T21:33:16.030+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2022-10-13T21:33:16.032+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-10-13T21:33:16.052+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-13T21:33:16.061+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=trabalho2, task_id=also_run_this, execution_date=20221009T000000, start_date=20221013T213315, end_date=20221013T213316
[2022-10-13T21:33:16.093+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task also_run_this (Bash command failed. The command returned a non-zero exit code 2.; 285)
[2022-10-13T21:33:16.126+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-13T21:33:16.205+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
